### ISSUE TITLE
Support `brew install --cask`

### ISSUE THREAD

**Issue by doi-t** [shihanng/terraform-provider-installer#42]
It seems that the `installer_brew` resource (i.e. [`brew install`](https://github.com/shihanng/terraform-provider-installer/blob/v0.3.0/internal/brew/brew.go#L14)) prioritize `formula` over `cask`.

For example, I wanted to install Docker for Mac Desktop app but `docker` formula package got install when I give `docker` as a `name` of `installer_brew`.
Since their name is the same, I need a way to optionally install it as a cask package.
- https://formulae.brew.sh/formula/docker
- https://formulae.brew.sh/cask/docker

I still can install other cask packages that has a unique name. But I would like always choose `cask` option for cask packages to explicitly install them as cask packages.

**Comment by shihanng** [comment]
I am addressing this in #80. Thank you for the feedback.
